### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to fetch.

### ISSUE THREAD

**Issue by mblonyox** [apicase/adapter-fetch#1]
Hey, first i just want to thanks for this great library.

At first I thought that the fetch error will be caught on error event bus defined in the service. But I guess the error only throwed in the promise. I think it will be great if it could handled in 'error' event bus.
I've read the docs that say you'll do the 'Improve errors logging' as you put it in the roadmap. I hope that it'll be done asap.

**Comment by Kelin2025** [comment]
Hey, thanks for you suggestion!  
I will take a look on these weekends ;)

**Comment by bragma** [comment]
Hi,
I still have the exact same problem, did you had time to look into it?

**Comment by Kelin2025** [comment]
Working on this way right now. Sorry for so huge delay

**Comment by Kelin2025** [comment]
I think these errors should be thrown by request function. Ofc I'll add it to 'error' event bus but I'll also throw this error 'case it's not a "business-logic failure"

**Comment by Kelin2025** [comment]
Need some big rework of request flow in `@apicase/core`   
https://github.com/apicase/core/issues/23

**Comment by Kelin2025** [comment]
I rewritten some things and it seems to work now.  
But I temporary removed hook stack trace log on errors  
Please, update `@apicase/core` to `0.16.0-beta.2` and let me know if something is broken
cc @mblonyox  @bragma

**Comment by bragma** [comment]
Thanks! I'll try to get some time to test it

**Comment by Kelin2025** [comment]
😉

**Comment by Kelin2025** [comment]
I'll close this issue. If you still have some problems, create a new one or write here

**Comment by tartinesKiller** [comment]
Hi,
Sorry to dig-up this issue, but I got the same problem, when disconnected from network, I got in devtools console
`Uncaught (in promise) TypeError: Failed to fetch`
But I can't seems to catch it. 
I've got the latest versions of @apicase/adapter-fetch (0.15.1) and @apicase/core (0.17.2)
Does the behaviour have been reversed? 
Thanks in advance
