### ISSUE TITLE
Response headers

### ISSUE THREAD

**Issue by SergeyMiracle** [apicase/adapter-fetch#3]
Hi!
Can not figure out how to get response headers. I wanna get 'Content-Disposition' header, but header prop in response is empty. Any help?

**Comment by Kelin2025** [comment]
`result` has `headers` property that contains response headers (suddenly) 
```
const { result } = SomeService.doRequest(...)

console.log(result.headers)
```

But it may be empty because of
https://stackoverflow.com/a/44816592

**Comment by Kelin2025** [comment]
Also you have to use `headers.entries()` to get headers entries (like in native fetch):
![image](https://user-images.githubusercontent.com/4208480/43400305-0f08e96a-9416-11e8-8501-6e01b5bca606.png)

Should adapter get `.entries()` automatically? 🤔

**Comment by SergeyMiracle** [comment]
@Kelin2025 ok i see, it's coz Fetch API over CORS restriction. Even with `Access-Control-Expose-Headers: Content-Length, Content-Range, Content-Disposition` Headers in response is empty

**Comment by SergeyMiracle** [comment]
@Kelin2025 `fetch('http://erp.test:8080/crm/leads/export-budget/')
        .then(r => {
          console.log([...r.headers.entries()])
        })`

Well this works, maybe adapter should get .entries() automatically

**Comment by SergeyMiracle** [comment]
Works like this for now
```
r.headers.forEach((v, k) => {
            console.log(v, k)
          })
```
